# Generated by Django 2.0.7 on 2018-07-29 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo1',
        ),
    ]
