# Generated by Django 2.0.7 on 2018-07-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo1',
        ),
        migrations.AddField(
            model_name='todo',
            name='first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='second',
            field=models.BooleanField(default=False),
        ),
    ]
